name: Notifier

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Notifier
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}
        TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN }}
        INPUT_STATUS: ${{ job.status }}
      run: sh -c "$(curl -sL https://raw.githubusercontent.com/athul/autom/master/tg_gh_action_noti.sh)"
